# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TikiTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire' 
  # Pods for TikiTest

  target 'TikiTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TikiTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
